name: walky
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  flutter_tts: ^4.2.3
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3
  http: ^1.5.0
  kakao_map_sdk: ^1.1.4



  cloud_firestore: ^6.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
        - asset: assets/fonts/Pretendard-Light.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Thin.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  # color와 background_image 속성은 둘 중 하나만 쓸 수 있음
  color: "#FFFFFF"
  image: assets/img/walky_icon_2.png     # ← PNG로 내보낸 파일

  android_12:
    color: "#FFFFFF"
    image: assets/img/walky_icon_2.png


  # 정렬(선택)
  android_gravity: center              # center, top, bottom, left, right, fill, bottom|center_horizontal 등
  ios_content_mode: center             # scaleToFill / scaleAspectFit / center ...


